### ISSUE TITLE
Image diagram

### ISSUE THREAD

**Issue by Light7734** [David-DiGioia/vulkan-diagrams#2]
May I recommend adding the diagram posted in this Stackoverflow question: [What is the difference between framebuffer and image in Vulkan?](https://stackoverflow.com/questions/39557141/what-is-the-difference-between-framebuffer-and-image-in-vulkan)

**Comment by David-DiGioia** [comment]
Thanks for the suggestion. It's funny you suggest that diagram, because that's the one that inspired me to start making my own. In fact, you can see my comment under that post says

> Thanks! Also what tool did you use to make the diagram? I'm thinking of making diagrams of other concepts in Vulkan because having it laid out visually is tremendously helpful in understanding for me.

And then the Vulkan diagrams repo was born. As far as including that, or other third party diagrams, I've thought about it. I do like having the diagrams all have a cohesive style and legend, so you can glance at any of the diagrams and instantly decipher it. Also I would want to make sure other authors are ok with me featuring their diagrams here.

Thanks for the feedback, I'm glad to hear others opinions on this.
